# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'netcore-api-docker:$(Build.BuildId)'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.402'

  - script: dotnet build --configuration $(buildConfiguration)

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - script: |
      cd netcore-api-docker.Api.UnitTests
      coverlet ./bin/Debug/netcoreapp2.1/netcore-api-docker-Api.UnitTests.dll --target "dotnet" --targetargs "test --no-build" --output ../coverage.json
      cd ..
      cd netcore-api-docker.Api.IntegrationTests
      coverlet ./bin/Debug/netcoreapp2.1/netcore-api-docker-Api.IntegrationTests.dll --target "dotnet" --targetargs "test --no-build" --merge-with ../coverage.json

  #- script: docker build -t $(imageName) ./netcore-api-docker.Api
