# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'netcore-api-docker:$(Build.BuildId)'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.402'

  - script: dotnet build --configuration $(buildConfiguration)

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - script: |
      mkdir $(Build.SourcesDirectory)\coverage
      cd netcore-api-docker.Api.UnitTests
      dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)\coverage\results.json
      cd ../netcore-api-docker.Api.IntegrationTests
      dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:p:MergeWith=$(Build.SourcesDirectory)\coverage\results.json

  #- script: docker build -t $(imageName) ./netcore-api-docker.Api
