# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'netcore-api-docker:$(Build.BuildId)'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.402'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration) build# $(Build.BuildId)'

  - script: |
      mkdir $(Build.SourcesDirectory)\coverage
      dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)\coverage\results.xml netcore-api-docker.Api.UnitTests
      dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:MergeWith=$(Build.SourcesDirectory)\coverage\results.xml netcore-api-docker.Api.IntegrationTests
    displayName: 'Tests'
  #- script: docker build -t $(imageName) ./netcore-api-docker.Api
