# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'netcore-api-docker:$(Build.BuildId)'

steps:
  - task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.402' # replace this value with the version that you need for your project

  - script: dotnet build --configuration $(buildConfiguration)

  - script: docker build -t $(imageName) .
